name: Generate Snake Game

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Game
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake Game SVG
        uses: Platane/snk@v0.3.0  # Replace with the desired version tag
        with:
          github_user_name: DhaniAM
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: "#FFA500"  # Orange color
          dot_color: "#008080"    # Teal color

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
