# name: Generate Snake

# on:
#   schedule: # execute at 18.00 everyday
#     - cron: "0 18 * * *"
#   workflow_dispatch:

# jobs:
#   build:
#     name: Jobs to update data
#     runs-on: ubuntu-latest
#     steps:
#       # Snake Animation
#       - uses: Platane/snk@master
#         id: snake-gif
#         with:
#           github_user_name: DhaniAM
#           color_snake: white
#           color_dots: red, green, blue, yellow, purple
#           svg_out_path: dist/github-contribution-grid-snake.svg

#       - uses: crazy-max/ghaction-github-pages@v2.1.3
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: Generate Snake Game

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Game
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Generate Snake Game SVG
      #   uses: Platane/snk@master
      #   with:
      #     github_user_name: DhaniAM
      #     svg_out_path: dist/github-contribution-grid-snake.svg
      #     snake_color: "#FFA500"  # Orange color
      #     dot_color: "#008080"    # Teal color
      - name: Generate Snake Game SVG
        run: |
          output=$(Platane/snk@master --github-user-name DhaniAM --svg-out-path dist/github-contribution-grid-snake.svg --snake-color "#FFA500" --dot-color "#008080")
          echo "::set-output name=generated_output::$output"


      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
